image: node:latest

pages:
    stage: deploy
    script:
        - yarn install
        - yarn build
        - echo $CI_PROJECT_DIR
    artifacts:
        paths:
            - build
    only:
        - master