image: node:latest

pages:
    stage: build
    script:
        - yarn install
        - yarn build
        - echo $CI_PROJECT_DIR
        - echo $CI_PROJECT_PATH_SLUG	
        - echo $CI_PROJECT_NAME	
    artifacts:
        paths:
            - public
    only:
        - master